version: '3.4'
services:
  grafana:
    image: grafana/grafana:7.5.3
    volumes:
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
     - GF_AUTH_ANONYMOUS_ENABLED=true
     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
     - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
     - 0.0.0.0:3000:3000

  prometheus:
    image: yeya24/prometheus:pyroscope
    user: root
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=1d
      - --enable-feature=exemplar-storage
      - --log.level=debug
      - --web.enable-admin-api
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 0.0.0.0:9090:9090
    environment:
      - pyroscope_app_name=prometheus
      - pyroscope_server_addr=http://pyroscope:4040

  thanos_sidecar:
    image: yeya24/thanos:pyroscope
    command:
      - "sidecar"
      - "--prometheus.url=http://prometheus:9090"
      - "--tracing.config-file=/etc/trace-sidecar.yaml"
    volumes:
      - ./trace-sidecar.yaml:/etc/trace-sidecar.yaml
    expose:
      - 10902
      - 10901
    environment:
      - pyroscope_app_name=thanos-sidecar
      - pyroscope_server_addr=http://pyroscope:4040

  thanos_querier:
    image: yeya24/thanos:pyroscope
    command:
      - "query"
      - "--store=thanos_sidecar:10901"
      - "--exemplar=thanos_sidecar:10901"
      - "--tracing.config-file=/etc/trace-query.yaml"
    volumes:
      - ./trace-query.yaml:/etc/trace-query.yaml
    expose:
      - 10902
      - 10901
    ports:
      - "10902:10902"
    environment:
      - pyroscope_app_name=thanos-querier
      - pyroscope_server_addr=http://pyroscope:4040

  pyroscope:
    image: pyroscope/pyroscope:latest
    command:
      - "server"
    expose:
      - 4040
    ports:
      - "4040:4040"

  node_exporter:
    image: prom/node-exporter:v1.1.0
    container_name: node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'

  tempo:
    image: grafana/tempo:0.7.0
    volumes:
      - ./tempo.yaml:/etc/tempo/config/config.yaml
    command:
      - "-config.file=/etc/tempo/config/config.yaml"
    ports:
      - "14268:14268"  # jaeger ingest
      - "6831:6831"
